# Predicting House Sale Prices

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold

In [2]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")

In [3]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
Order              2930 non-null int64
PID                2930 non-null int64
MS SubClass        2930 non-null int64
MS Zoning          2930 non-null object
Lot Frontage       2440 non-null float64
Lot Area           2930 non-null int64
Street             2930 non-null object
Alley              198 non-null object
Lot Shape          2930 non-null object
Land Contour       2930 non-null object
Utilities          2930 non-null object
Lot Config         2930 non-null object
Land Slope         2930 non-null object
Neighborhood       2930 non-null object
Condition 1        2930 non-null object
Condition 2        2930 non-null object
Bldg Type          2930 non-null object
House Style        2930 non-null object
Overall Qual       2930 non-null int64
Overall Cond       2930 non-null int64
Year Built         2930 non-null int64
Year Remod/Add     2930 non-null int64
Roof Style         2930 non-null object
Roof Matl          2930 non-null object
Exterior 1st       2930 non-null object
Exterior 2nd       2930 non-null object
Mas Vnr Type       2907 non-null object
Mas Vnr Area       2907 non-null float64
Exter Qual         2930 non-null object
Exter Cond         2930 non-null object
Foundation         2930 non-null object
Bsmt Qual          2850 non-null object
Bsmt Cond          2850 non-null object
Bsmt Exposure      2847 non-null object
BsmtFin Type 1     2850 non-null object
BsmtFin SF 1       2929 non-null float64
BsmtFin Type 2     2849 non-null object
BsmtFin SF 2       2929 non-null float64
Bsmt Unf SF        2929 non-null float64
Total Bsmt SF      2929 non-null float64
Heating            2930 non-null object
Heating QC         2930 non-null object
Central Air        2930 non-null object
Electrical         2929 non-null object
1st Flr SF         2930 non-null int64
2nd Flr SF         2930 non-null int64
Low Qual Fin SF    2930 non-null int64
Gr Liv Area        2930 non-null int64
Bsmt Full Bath     2928 non-null float64
Bsmt Half Bath     2928 non-null float64
Full Bath          2930 non-null int64
Half Bath          2930 non-null int64
Bedroom AbvGr      2930 non-null int64
Kitchen AbvGr      2930 non-null int64
Kitchen Qual       2930 non-null object
TotRms AbvGrd      2930 non-null int64
Functional         2930 non-null object
Fireplaces         2930 non-null int64
Fireplace Qu       1508 non-null object
Garage Type        2773 non-null object
Garage Yr Blt      2771 non-null float64
Garage Finish      2771 non-null object
Garage Cars        2929 non-null float64
Garage Area        2929 non-null float64
Garage Qual        2771 non-null object
Garage Cond        2771 non-null object
Paved Drive        2930 non-null object
Wood Deck SF       2930 non-null int64
Open Porch SF      2930 non-null int64
Enclosed Porch     2930 non-null int64
3Ssn Porch         2930 non-null int64
Screen Porch       2930 non-null int64
Pool Area          2930 non-null int64
Pool QC            13 non-null object
Fence              572 non-null object
Misc Feature       106 non-null object
Misc Val           2930 non-null int64
Mo Sold            2930 non-null int64
Yr Sold            2930 non-null int64
Sale Type          2930 non-null object
Sale Condition     2930 non-null object
SalePrice          2930 non-null int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [5]:
#creating functions that will facilitate features selection and creating model
#picking linear regaression model
def transform_features(df):
    return df

def select_features(df):
    return df[['Gr Liv Area', 'SalePrice']]

def train_and_test(df):
    train = df.copy().iloc[0:1460]
    test = df.copy().iloc[1460:]
    
    numeric_train = train.select_dtypes(include=['integer', 'float'])
    numeric_test = test.select_dtypes(include=['integer', 'float'])
    
    #linear model training
    features = numeric_train.columns.drop('SalePrice')
    target = 'SalePrice'
    model = LinearRegression()
    model.fit(train[features], train[target])
    
    #prediction and returning error metrics
    prediction = model.predict(test[features])
    mse = mean_squared_error(test[target], prediction)
    rmse = np.sqrt(mse)
    return rmse

In [6]:
#testing proper work of functions
transformed_df = transform_features(df)
filtered_df = select_features(transformed_df)
rmse = train_and_test(filtered_df)
print(rmse)

57088.25161263909

## Features enginnering

1. All columns: removing if contains more than 5% of null values
2. Text columns: removing if contain at least 1 missing value (will note be useful during categorization od data)
3. Numeric columns: replacing remaining missing values with most common value

In [7]:
#checking up null values:
all_nulls = df.isnull().sum()
all_nulls[all_nulls > 0]

Lot Frontage       490
Alley             2732
Mas Vnr Type        23
Mas Vnr Area        23
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin SF 1         1
BsmtFin Type 2      81
BsmtFin SF 2         1
Bsmt Unf SF          1
Total Bsmt SF        1
Electrical           1
Bsmt Full Bath       2
Bsmt Half Bath       2
Fireplace Qu      1422
Garage Type        157
Garage Yr Blt      159
Garage Finish      159
Garage Cars          1
Garage Area          1
Garage Qual        159
Garage Cond        159
Pool QC           2917
Fence             2358
Misc Feature      2824
dtype: int64

In [8]:
#droping columns containing more than 5% of nulls
drop_null_cols = all_nulls[all_nulls > len(df)/20].sort_values()

df = df.drop(drop_null_cols.index, axis=1)

In [9]:
#dropping text columns containing at least one null value
text_null_counts = df.select_dtypes(include='object').isnull().sum().sort_values(ascending=False)
text_cols_drop = text_null_counts[text_null_counts > 0]

df = df.drop(text_cols_drop.index, axis=1)

In [10]:
#for numeric columns replacing missing values with most common value
#firstly selecting numeric columns that contain nulls
num_cols = df.select_dtypes(include=['int', 'float']).isnull().sum().sort_values(ascending=False)

num_cols

Mas Vnr Area      23
Bsmt Half Bath     2
Bsmt Full Bath     2
Garage Area        1
Garage Cars        1
Total Bsmt SF      1
Bsmt Unf SF        1
BsmtFin SF 2       1
BsmtFin SF 1       1
dtype: int64

In [11]:
#creating dictionary with most common value for each numeric col with nulls
replacement_dict = df[num_cols.index].mode().to_dict(orient='records')[0]

replacement_dict

{'Mas Vnr Area': 0.0,
 'Bsmt Half Bath': 0.0,
 'Bsmt Full Bath': 0.0,
 'Garage Area': 0.0,
 'Garage Cars': 2.0,
 'Total Bsmt SF': 0.0,
 'Bsmt Unf SF': 0.0,
 'BsmtFin SF 2': 0.0,
 'BsmtFin SF 1': 0.0}

In [12]:
#replacing nulls in numeric cols with mode (most common value)
df = df.fillna(replacement_dict)

In [13]:
#proving there is now no nulls in df as command returns empty Series object
df.isnull().sum()[df.isnull().sum()>0]

Series([], dtype: int64)

In [14]:
#retrieving useful information from columns related to Years
#checking potential incorrect records
years_sold = df['Yr Sold'] - df['Year Built']
years_sold[years_sold < 0]

2180   -1
dtype: int64

In [15]:
#retrieving useful info about columns 'Years since remod'
years_remod = df['Yr Sold'] - df['Year Remod/Add']
years_remod[years_remod < 0]

1702   -1
2180   -2
2181   -1
dtype: int64

In [16]:
#creating new columns in dataframe
df['Years Before Sell'] = years_sold
df['Years Since Remod'] = years_remod

#removing rows with incorrect data
df.drop([1702,2180,2181], axis=0)

#original columns with Years are no longer needed hence remove
df.drop(['Year Built', 'Year Remod/Add'], axis=1)

,Order,PID,MS SubClass,MS Zoning,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,...,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice,Years Before Sell,Years Since Remod
0,1,526301100,20,RL,31770,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,5,2010,WD,Normal,215000,50,50
1,2,526350040,20,RH,11622,Pave,Reg,Lvl,AllPub,Inside,...,120,0,0,6,2010,WD,Normal,105000,49,49
2,3,526351010,20,RL,14267,Pave,IR1,Lvl,AllPub,Corner,...,0,0,12500,6,2010,WD,Normal,172000,52,52
3,4,526353030,20,RL,11160,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,4,2010,WD,Normal,244000,42,42
4,5,527105010,60,RL,13830,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,3,2010,WD,Normal,189900,13,12
5,6,527105030,60,RL,9978,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,6,2010,WD,Normal,195500,12,12
6,7,527127150,120,RL,4920,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,4,2010,WD,Normal,213500,9,9
7,8,527145080,120,RL,5005,Pave,IR1,HLS,AllPub,Inside,...,144,0,0,1,2010,WD,Normal,191500,18,18
8,9,527146030,120,RL,5389,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,3,2010,WD,Normal,236500,15,14
9,10,527162130,60,RL,7500,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,6,2010,WD,Normal,189000,11,11
10,11,527163010,60,RL,10000,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,4,2010,WD,Normal,175900,17,16
11,12,527165230,20,RL,7980,Pave,IR1,Lvl,AllPub,Inside,...,0,0,500,3,2010,WD,Normal,185000,18,3
12,13,527166040,60,RL,8402,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,5,2010,WD,Normal,180400,12,12
13,14,527180040,20,RL,10176,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,2,2010,WD,Normal,171500,20,20
14,15,527182190,120,RL,6820,Pave,IR1,Lvl,AllPub,Corner,...,140,0,0,6,2010,WD,Normal,212000,25,25
15,16,527216070,60,RL,53504,Pave,IR2,HLS,AllPub,CulDSac,...,210,0,0,6,2010,WD,Normal,538000,7,7
16,17,527225035,50,RL,12134,Pave,IR1,Bnk,AllPub,Inside,...,0,0,0,6,2010,WD,Normal,164000,22,5
17,18,527258010,20,RL,11394,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,6,2010,New,Partial,394432,0,0
18,19,527276150,20,RL,19138,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,6,2010,WD,Normal,141000,59,59
19,20,527302110,20,RL,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,2,2010,WD,Normal,210000,32,22
20,21,527358140,20,RL,11751,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,1,2010,COD,Normal,190000,33,33
21,22,527358200,85,RL,10625,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,1,2010,WD,Family,170000,36,36
22,23,527368020,60,FV,7500,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,1,2010,WD,Normal,216000,10,10
23,24,527402200,20,RL,11241,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,700,3,2010,WD,Normal,149000,40,40
24,25,527402250,20,RL,12537,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,4,2010,WD,Normal,149900,39,2
25,26,527403020,20,RL,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,7,2010,WD,Normal,142000,42,42
26,27,527404120,20,RL,8400,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,4,2010,WD,Normal,126000,40,40
27,28,527425090,20,RL,10500,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,4,2010,ConLI,Normal,115000,39,39
28,29,527427230,120,RH,5858,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,6,2010,WD,Normal,184000,11,11
29,30,527451180,160,RM,1680,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,2,2010,COD,Normal,96000,39,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2901,916477010,20,RL,13618,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,11,2006,New,Partial,320000,1,0
2901,2902,921205030,20,RL,11443,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,3,2006,New,Partial,369900,1,0
2902,2903,921205050,20,RL,11577,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,9,2006,New,Partial,359900,1,0
2903,2904,923125030,20,A (agr),31250,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,5,2006,WD,Normal,81500,55,55
2904,2905,923202025,90,RM,7020,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,11,2006,WD,Normal,215000,9,9
2905,2906,923203090,120,RM,4500,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,5,2006,WD,Normal,164000,8,8
2906,2907,923203100,120,RM,4500,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,3,2006,WD,Normal,153500,8,8
2907,2908,923205120,20,RL,17217,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,7,2006,WD,Abnorml,84500,0,0
2908,2909,923225190,160,RM,2665,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,5,2006,WD,Normal,104500,29,29
2909,2910,923225240,160,RM,2665,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,7,2006,WD,Normal,127000,29,29
2910,2911,923225260,160,RM,3964,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,6,2006,WD,Normal,151400,33,33
2911,2912,923225510,20,RL,10172,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,10,2006,WD,Normal,126500,38,3
2912,2913,923226150,90,RL,11836,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,3,2006,WD,Normal,146500,36,36
2913,2914,923226180,180,RM,1470,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,4,2006,WD,Normal,73000,36,36
2914,2915,923226290,160,RM,1484,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,5,2006,WD,Normal,79400,34,34
2915,2916,923227100,20,RL,13384,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,5,2006,WD,Normal,140000,37,27
2916,2917,923228130,180,RM,1533,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,8,2006,WD,Abnorml,92000,36,36
2917,2918,923228180,160,RM,1533,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,12,2006,WD,Abnorml,87550,36,36
2918,2919,923228210,160,RM,1526,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,6,2006,WD,Normal,79500,36,36
2919,2920,923228260,160,RM,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,6,2006,WD,Normal,90500,36,36
2920,2921,923228310,160,RM,1894,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,4,2006,WD,Abnorml,71000,36,36
2921,2922,923229110,90,RL,12640,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,7,2006,WD,Normal,150900,30,30
2922,2923,923230040,90,RL,9297,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,7,2006,WD,Family,188000,30,30
2923,2924,923250060,20,RL,17400,Pave,Reg,Low,AllPub,Inside,...,0,0,0,5,2006,WD,Normal,160000,29,29
2924,2925,923251180,20,RL,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,9,2006,WD,Abnorml,131000,46,10
2925,2926,923275080,80,RL,7937,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,3,2006,WD,Normal,142500,22,22
2926,2927,923276100,20,RL,8885,Pave,IR1,Low,AllPub,Inside,...,0,0,0,6,2006,WD,Normal,131000,23,23
2927,2928,923400125,85,RL,10441,Pave,Reg,Lvl,AllPub,Inside,...,0,0,700,7,2006,WD,Normal,132000,14,14
2928,2929,924100070,20,RL,10010,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,4,2006,WD,Normal,170000,32,31
2929,2930,924151050,60,RL,9627,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,11,2006,WD,Normal,188000,13,12

In [17]:
#dropping columns that are meaningless from ML perspective
df = df.drop(["PID", "Order"], axis=1)

#dropping columns that not contain information regarding final sale
df = df.drop(["Mo Sold", "Sale Condition", "Sale Type", "Yr Sold"], axis=1)

In [18]:
#updating transform_feature() function in pipeline of functions

def transform_features(df):
    num_missing = df.isnull().sum()
    drop_missing_cols = num_missing[(num_missing > len(df)/20)].sort_values()
    df = df.drop(drop_missing_cols.index, axis=1)
    
    text_mv_counts = df.select_dtypes(include=['object']).isnull().sum().sort_values(ascending=False)
    drop_missing_cols_2 = text_mv_counts[text_mv_counts > 0]
    df = df.drop(drop_missing_cols_2.index, axis=1)
    
    num_missing = df.select_dtypes(include=['int', 'float']).isnull().sum()
    fixable_numeric_cols = num_missing[(num_missing < len(df)/20) & (num_missing > 0)].sort_values()
    replacement_values_dict = df[fixable_numeric_cols.index].mode().to_dict(orient='records')[0]
    df = df.fillna(replacement_values_dict)
    
    years_sold = df['Yr Sold'] - df['Year Built']
    years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
    df['Years Before Sale'] = years_sold
    df['Years Since Remod'] = years_since_remod
    df = df.drop([1702, 2180, 2181], axis=0)

    df = df.drop(["PID", "Order", "Mo Sold", "Sale Condition", "Sale Type", "Year Built", "Year Remod/Add"], axis=1)
    return df

def select_features(df):
    return df[['Gr Liv Area', 'SalePrice']]

def train_and_test(df):
    train = df.copy().iloc[0:1460]
    test = df.copy().iloc[1460:]
    
    numeric_train = train.select_dtypes(include=['integer', 'float'])
    numeric_test = test.select_dtypes(include=['integer', 'float'])
    
    #linear model training
    features = numeric_train.columns.drop('SalePrice')
    target = 'SalePrice'
    model = LinearRegression()
    model.fit(train[features], train[target])
    
    #prediction and returning error metrics
    prediction = model.predict(test[features])
    mse = mean_squared_error(test[target], prediction)
    rmse = np.sqrt(mse)
    return rmse

df = pd.read_csv("AmesHousing.tsv", delimiter="\t")

trans_df = transform_features(df)
select_df = select_features(trans_df)
rmse = train_and_test(select_df)

print(rmse)

55275.367312413066

## Features selection

In [19]:
num_df = trans_df.select_dtypes(include=['integer','float'])
num_df.head()

,MS SubClass,Lot Area,Overall Qual,Overall Cond,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,...,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Yr Sold,SalePrice,Years Before Sale,Years Since Remod
0,20,31770,6,5,112.0,639.0,0.0,441.0,1080.0,1656,...,62,0,0,0,0,0,2010,215000,50,50
1,20,11622,5,6,0.0,468.0,144.0,270.0,882.0,896,...,0,0,0,120,0,0,2010,105000,49,49
2,20,14267,6,6,108.0,923.0,0.0,406.0,1329.0,1329,...,36,0,0,0,0,12500,2010,172000,52,52
3,20,11160,7,5,0.0,1065.0,0.0,1045.0,2110.0,2110,...,0,0,0,0,0,0,2010,244000,42,42
4,60,13830,5,5,0.0,791.0,0.0,137.0,928.0,928,...,34,0,0,0,0,0,2010,189900,13,12

In [20]:
#calculating the correlation between feature columns and target column (SalePrice)
#keeping only correlations below certain threshold

corr_coefs_abs = num_df.corr()['SalePrice'].abs().sort_values(ascending = False)
corr_coefs_abs[corr_coefs_abs > 0.5]

SalePrice            1.000000
Overall Qual         0.801206
Gr Liv Area          0.717596
Garage Cars          0.648361
Total Bsmt SF        0.644012
Garage Area          0.641425
1st Flr SF           0.635185
Years Before Sale    0.558979
Full Bath            0.546118
Years Since Remod    0.534985
Mas Vnr Area         0.506983
Name: SalePrice, dtype: float64

In [21]:
#dropping columns with less than 0.5 correlation coefficient
trans_df = trans_df.drop(corr_coefs_abs[corr_coefs_abs < 0.5].index, axis=1)

In [22]:
#list of categorical columns
categors = ["PID", "MS SubClass", "MS Zoning", "Street", "Alley", "Land Contour", "Lot Config", "Neighborhood", 
            "Condition 1", "Condition 2", "Bldg Type", "House Style", "Roof Style", "Roof Matl", "Exterior 1st", 
            "Exterior 2nd", "Mas Vnr Type", "Foundation", "Heating", "Central Air", "Garage Type", 
            "Misc Feature", "Sale Type", "Sale Condition"]

In [23]:
#checking which of categorical columns are still present in dataset after using transforming function

transform_categorical = []
for col in categors:
    if col in trans_df.columns:
        transform_categorical.append(col)

In [24]:
#looking the number of unique values in each categorical column
unique_counts = trans_df[transform_categorical].apply(lambda c : len(c.value_counts())).sort_values()

In [25]:
#arbitrarly cutting of on 10 unique values

drop_cat = unique_counts[unique_counts > 10].index
trans_df = trans_df.drop(drop_cat, axis=1)

In [26]:
#conversion of remaining text cols to categorical
text_cols = trans_df.select_dtypes(include=['object'])

for col in text_cols:
    trans_df[col] = trans_df[col].astype('category')

In [27]:
#creating dummy columns and adding it back to original dataframe
trans_df = pd.concat([
    trans_df, 
    pd.get_dummies(trans_df.select_dtypes(include=['category']))
], axis=1).drop(text_cols,axis=1)

In [28]:
trans_df.head()

,Overall Qual,Mas Vnr Area,Total Bsmt SF,1st Flr SF,Gr Liv Area,Full Bath,Garage Cars,Garage Area,SalePrice,Years Before Sale,...,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sal,Functional_Sev,Functional_Typ,Paved Drive_N,Paved Drive_P,Paved Drive_Y
0,6,112.0,1080.0,1656,1656,1,2.0,528.0,215000,50,...,0,0,0,0,0,0,1,0,1,0
1,5,0.0,882.0,896,896,1,1.0,730.0,105000,49,...,0,0,0,0,0,0,1,0,0,1
2,6,108.0,1329.0,1329,1329,1,1.0,312.0,172000,52,...,0,0,0,0,0,0,1,0,0,1
3,7,0.0,2110.0,2110,2110,2,2.0,522.0,244000,42,...,0,0,0,0,0,0,1,0,0,1
4,5,0.0,928.0,928,1629,2,2.0,482.0,189900,13,...,0,0,0,0,0,0,1,0,0,1

## Updating train_and_test() function

In [38]:
#updating select_features function with recent steps

def transform_features(df):
    num_missing = df.isnull().sum()
    drop_missing_cols = num_missing[(num_missing > len(df)/20)].sort_values()
    df = df.drop(drop_missing_cols.index, axis=1)
    
    text_mv_counts = df.select_dtypes(include=['object']).isnull().sum().sort_values(ascending=False)
    drop_missing_cols_2 = text_mv_counts[text_mv_counts > 0]
    df = df.drop(drop_missing_cols_2.index, axis=1)
    
    num_missing = df.select_dtypes(include=['int', 'float']).isnull().sum()
    fixable_numeric_cols = num_missing[(num_missing < len(df)/20) & (num_missing > 0)].sort_values()
    replacement_values_dict = df[fixable_numeric_cols.index].mode().to_dict(orient='records')[0]
    df = df.fillna(replacement_values_dict)
    
    years_sold = df['Yr Sold'] - df['Year Built']
    years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
    df['Years Before Sale'] = years_sold
    df['Years Since Remod'] = years_since_remod
    df = df.drop([1702, 2180, 2181], axis=0)

    df = df.drop(["PID", "Order", "Mo Sold", "Sale Condition", "Sale Type", "Year Built", "Year Remod/Add"], axis=1)
    return df


def select_features(df, coeff_threshold=0.5, uniq_threshold=10):
    numerical_df = df.select_dtypes(include=['integer', 'float'])
    abs_corr_coeffs = numerical_df.corr()['SalePrice'].abs().sort_values()
    df = df.drop(abs_corr_coeffs[abs_corr_coeffs < coeff_threshold].index, axis=1)
    
    nominal_features = ["PID", "MS SubClass", "MS Zoning", "Street", "Alley", "Land Contour", "Lot Config", "Neighborhood", 
                    "Condition 1", "Condition 2", "Bldg Type", "House Style", "Roof Style", "Roof Matl", "Exterior 1st", 
                    "Exterior 2nd", "Mas Vnr Type", "Foundation", "Heating", "Central Air", "Garage Type", 
                    "Misc Feature", "Sale Type", "Sale Condition"]
    
    transform_cat_cols = []
    for col in nominal_features:
        if col in df.columns:
            transform_cat_cols.append(col)

    uniqueness_counts = df[transform_cat_cols].apply(lambda col: len(col.value_counts())).sort_values()
    drop_nonuniq_cols = uniqueness_counts[uniqueness_counts > 10].index
    df = df.drop(drop_nonuniq_cols, axis=1)
    
    text_cols = df.select_dtypes(include=['object'])
    for col in text_cols:
        df[col] = df[col].astype('category')
    df = pd.concat([df, pd.get_dummies(df.select_dtypes(include=['category']))], axis=1).drop(text_cols,axis=1)
    
    return df

def train_and_test(df, k=0):
    numeric_df = df.select_dtypes(include=['integer', 'float'])
    features = numeric_df.columns.drop("SalePrice")
    lr = LinearRegression()
    
    if k == 0:
        train = df[:1460]
        test = df[1460:]

        lr.fit(train[features], train["SalePrice"])
        predictions = lr.predict(test[features])
        mse = mean_squared_error(test["SalePrice"], predictions)
        rmse = np.sqrt(mse)

        return rmse
    
    if k == 1:
        # Randomize *all* rows (frac=1) from `df` and return
        shuffled_df = df.sample(frac=1, )
        train = df[:1460]
        test = df[1460:]
        
        lr.fit(train[features], train["SalePrice"])
        predictions_one = lr.predict(test[features])        
        
        mse_one = mean_squared_error(test["SalePrice"], predictions_one)
        rmse_one = np.sqrt(mse_one)
        
        lr.fit(test[features], test["SalePrice"])
        predictions_two = lr.predict(train[features])        
       
        mse_two = mean_squared_error(train["SalePrice"], predictions_two)
        rmse_two = np.sqrt(mse_two)
        
        avg_rmse = np.mean([rmse_one, rmse_two])
        print(rmse_one)
        print(rmse_two)
        return avg_rmse
    #performing K-Fold cross validation
    else:
        kf = KFold(n_splits=k, shuffle=True)
        rmse_values = []
        for train_index, test_index, in kf.split(df):
            train = df.iloc[train_index]
            test = df.iloc[test_index]
            lr.fit(train[features], train["SalePrice"])
            predictions = lr.predict(test[features])
            mse = mean_squared_error(test["SalePrice"], predictions)
            rmse = np.sqrt(mse)
            rmse_values.append(rmse)
        print(rmse_values)
        avg_rmse = np.mean(rmse_values)
        return avg_rmse
    
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
transform_df = transform_features(df)
select_df = select_features(transform_df)
rmse = train_and_test(select_df, k=6)

rmse

[26281.995854465982, 25974.45469765258, 39861.27808327968, 31034.689195929885, 27466.95771693375, 30140.10000511974]

30126.579258896934